envs:
- BITRISE_CERTIFICATE_URL: file:///Users/lpusok/ExportedAppleCerts/AppleDevelopmentLP.p12|file:///Users/lpusok/ExportedAppleCerts/AppleDistributionBF.p12
- BITRISE_CERTIFICATE_PASSPHRASE: "|"

- BITRISE_BUILD_URL: file://$HOME/apple_developer_portal_data_developer.json
- BITRISE_BUILD_API_TOKEN: "-xxx-xxxxx"

- BITRISE_KEYCHAIN_PATH: $HOME/Library/Keychains/autoprov-test.keychain
- BITRISE_KEYCHAIN_PASSWORD: autoprov-test
